apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-index-html-configmap
  #namespace: {{ .Chart.Name }}-{{ .Values.namespace }}
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! I got deployed from {{ .Values.env.name }} app using Helm Chart </h1>
    </html
