#sample-values1.yaml
rbac:
  dev:
    elevatedgroupId: # Group Ids having deploy access
      - 2f32f01c-ae64-4072-8fcd-234ba3ed7eb9 # cloud engineering
      - 2da22b4c-6166-440b-9af3-011f43ad8217 # partior-engineering
    groupId: # read-only role
      - e1eb86cb-714a-4768-8f23-2a8946db3bdd # cloud engineering non-prod
      - f7cf6441-3a69-4f31-8340-f6f8fcdfaa68 # app-sre
      - 2da22b4c-6166-440b-9af3-011f43ad8217 # partior-engineering
  uat:
    elevatedgroupId: # Group Ids having deploy access
      - f7cf6441-3a69-4f31-8340-f6f8fcdfaa68 # app-sre
    groupId: # read-only role
      - 2f32f01c-ae64-4072-8fcd-234ba3ed7eb9 # cloud engineering
      - e1eb86cb-714a-4768-8f23-2a8946db3bdd # cloud engineering non-prod
      - 2da22b4c-6166-440b-9af3-011f43ad8217 # partior-engineering
  prod:
    elevatedgroupId: # Group Ids having deploy access
      - f7cf6441-3a69-4f31-8340-f6f8fcdfaa68 # app-sre
    groupId: # read-only role
      - 2f32f01c-ae64-4072-8fcd-234ba3ed7eb9 # cloud engineering
      - e1eb86cb-714a-4768-8f23-2a8946db3bdd # cloud engineering non-prod
      - 2da22b4c-6166-440b-9af3-011f43ad8217 # partior-engineering
 
clusterWorkloadsRepos:
  - name: partior-quorum-argo
    repoUrl: https://github.com/OpsMx/argo-customer-demo.git
    branch: testcase
    preserveResourcesOnDeletion: false
    enableNSResourcesExtra: true
    nsextra:
      "'elbv2.k8s.aws'":
        - TargetGroupBinding
  - name: partior-consul-argo
    repoUrl: https://github.com/OpsMx/argo-customer-demo.git 
    branch: testcase
    enableNSResourcesExtra: true
    nsextra:
      "'elbv2.k8s.aws'":
        - TargetGroupBinding
      "'consul.hashicorp.com'":
        - Mesh
        - ProxyDefaults
      "'apps'":
        - DaemonSet
      "''":
        - ResourceQuota
      #"'consul.hashicorp.com/v1alpha1'":
        #- Mesh
        #- ProxyDefaults
    enableCRD: true
    preserveResourcesOnDeletion: false
    crds:
      "'rbac.authorization.k8s.io'":
        - ClusterRole
        - ClusterRoleBinding
      "'autoscaling/v2'":
        - HorizontalPodAutoscaler
      "'admissionregistration.k8s.io'":
        - MutatingWebhookConfiguration
      "'apiextensions.k8s.io'":
        - CustomResourceDefinition
      "'consul.hashicorp.com/v1alpha1'":       
        - Mesh
        - PeeringAcceptor
        - PeeringDailer
        - TerminatingGateway
        - ServiceSplitter
        - ServiceRouter
        - ServiceResolver
        - ServiceIntentions
        - ServiceDefaults
        - ProxyDefaults
        - IngressGateway
        - ExportedServices
  - name: partior-quorum-dba-argo
    repoUrl: https://github.com/OpsMx/argo-customer-demo.git 
    branch: testcase
    preserveResourcesOnDeletion: false
